### ISSUE TITLE
Issue with send-spoofed-reply Command - Runtime Error: Index Out of Range

### ISSUE THREAD

**Issue by kuwaitq8kuwait** [lichti/whats-spoofing#20]
I encountered a runtime error while using the send-spoofed-reply command in your project. The specific error message is as follows:

goroutine 74 [running]:
main.cmdSendSpoofedReply({0xc0002e63d0, 0x4, 0x4})
        /usr/lib/win-kex/pulse/whats-spoofing/commands.go:82 +0x651
main.handleCmd1({0xc000182120, 0xc000192470?}, {0xc0002e63d0, 0x4, 0x4}, 0x0)
        /usr/lib/win-kex/pulse/whats-spoofing/main.go:171 +0x4c5
main.handleCmd({0xc000182120?, 0xc0001bd7d0?}, {0xc0002e63d0?, 0xc00028e000?, 0xc0004d8000?})
        /usr/lib/win-kex/pulse/whats-spoofing/main.go:158 +0x25
created by main.main in goroutine 1
        /usr/lib/win-kex/pulse/whats-spoofing/main.go:149 +0x933

This error occurs when executing the command with the following input:

Example :
send-spoofed-reply 4545454545 3EB071FA5C3CB75DB5F587 45454545454545 ar

Could you please look into this? It would be greatly appreciated if you could provide guidance on how to resolve this issue or if a fix could be implemented in the project. I believe correcting this error would enhance the tool's functionality and reliability for all users.

**Comment by eldarkace** [comment]
Did you know how to fix it?
